<a href="https://colab.research.google.com/github/rohitrepo1/pytorch/blob/master/pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [5]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6386, 0.5407, 0.9285, 0.3748],
        [0.8497, 0.4718, 0.6282, 0.6725],
        [0.0669, 0.5148, 0.5175, 0.2450]])

In [7]:
random_image_size = torch.rand(size=(224, 224, 3))
random_image_size.shape, random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
#create a tessor of all zeros
zeros = torch.zeros(size=(10, 20))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
#creating a range of tensor and tensor like 
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#craeting a range with start end and step
test_to_demo = torch.arange(start=10, end=100, step=5)
test_to_demo

tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [15]:
#creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
#tesnor datatype FLOAT
#32-bit floating point
float_32_tensor = torch.tensor([5.0, 6.0, 9.0],
                               dtype=None, # what type is the tensor
                               device=None, # what device your tensor on 
                               requires_grad=False) # weather or not to track 
float_32_tensor


tensor([5., 6., 9.])

NOTE: Tesnor datatype is one of the 3 big erros you  will run into with Pytroch ⛹ 

1. Tensor not right datatype

2. Tensor not right shape

3. Tensor not on the right Device 



In [21]:
#convert float32 tensot to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([5., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor 

tensor([25., 36., 81.])

## Getting information from tensor ###

Tensor not right datatype  - To do get data type from a tensor, can you `tensor.dtype`

Tensor not right shape - To get share from tensor use `tensor.shape`

Tensor not on the right Device -  To get device from tensor can use `tensor.device` 

In [28]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2038, 0.4268, 0.1561, 0.0975],
        [0.3972, 0.1110, 0.0364, 0.9809],
        [0.7203, 0.3673, 0.4706, 0.4652]])

In [30]:
print(f"device tensor is on : {some_tensor.device}")

device tensor is on : cpu


Manipulating Tensors
Tensor operation includes: 


*   addition
*   Subtraction 
*   Multiplication 
*   Dicision
*   Matrix Multiplication 
*   








In [31]:
tensor = torch.tensor([1, 2, 3])
tensor * 20 

tensor([20, 40, 60])

 Matrix Multiplication   `https://www.mathsisfun.com/algebra/matrix-multiplying.html`

 tow main way to perform Matrix Multiplication in neural network and deep Learning  


1.   Element-wise Multiplication
2.   Matrix  Multiplication(dot product)




In [32]:
tensor * tensor 

tensor([1, 4, 9])