<a href="https://colab.research.google.com/github/rohitrepo1/pytorch/blob/master/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("its amazing to learn pytorch")

its amazing to learn pytorch


In [ ]:
!nvidia-smi


Mon Mar 27 16:04:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
print(torch.__version__)

1.13.1+cu116


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
scalar.item()

7

In [ ]:
TENSOR = torch.tensor ([[[1,2,3],
                         [3,4,5],
                         [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensor 

why random tensor? 

Random tensor are important becase the way  many neural network works learn in that they start withe tensor full of random numbers and then adjust those random number to better represent the data. 

`start with random number > look at data > update random number > look at the data > update`


In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5257, 0.9284, 0.5293, 0.8947],
        [0.1311, 0.8171, 0.5163, 0.6743],
        [0.8589, 0.0096, 0.5267, 0.5995]])

In [ ]:
random_tensor.ndim

2